### ISSUE TITLE
 python train_SmaAtUNet.py  error :

### ISSUE THREAD

**Issue by wy22vv** [HansBambel/SmaAt-UNet#2]
No such file or directory: 'data/PascalVOC/VOCdevkit/VOC2012/ImageSets/Segmentation/train.txt
Are the documents provided incomplete?
in your file,i can not see the folder /data

**Comment by HansBambel** [comment]
Hey, thanks for opening the issue.

As I've written in the README.md the `train_SmaAtUNet.py` is just an example script on how to train the model using standard PyTorch. For this, I used a pretty common dataset called [PascalVOC](http://host.robots.ox.ac.uk/pascal/VOC/). When you have downloaded this dataset and placed it in the appropriate folder the script should work.

The training that was reported in the Paper used the `train_precip_lightning.py` script which, in addition to pytorch, used pytorch-lightning as well. I hope this helps!

**Comment by wy22vv** [comment]
> Hey, thanks for opening the issue.
> 
> As I've written in the README.md the `train_SmaAtUNet.py` is just an example script on how to train the model using standard PyTorch. For this, I used a pretty common dataset called [PascalVOC](http://host.robots.ox.ac.uk/pascal/VOC/). When you have downloaded this dataset and placed it in the appropriate folder the script should work.
> 
> The training that was reported in the Paper used the `train_precip_lightning.py` script which, in addition to pytorch, used pytorch-lightning as well. I hope this helps!



> Hey, thanks for opening the issue.
> 
> As I've written in the README.md the `train_SmaAtUNet.py` is just an example script on how to train the model using standard PyTorch. For this, I used a pretty common dataset called [PascalVOC](http://host.robots.ox.ac.uk/pascal/VOC/). When you have downloaded this dataset and placed it in the appropriate folder the script should work.
> 
> The training that was reported in the Paper used the `train_precip_lightning.py` script which, in addition to pytorch, used pytorch-lightning as well. I hope this helps!

My training process is like this, 
1 create a new folder dataprecipitation and then put the downloaded dataset in this folder, then put this folder in the file you uploaded, 
2 use the command
 pip install -r requirements.txt 
python create_datasets.py, 
python  train_precip_lightning.py
 but there were errors in the test and train_SmaAtUNet.py running,

**Comment by HansBambel** [comment]
That sounds like the right process. What are the errors that you encountered then?

**Comment by wy22vv** [comment]
At 2022-10-01 17:27:52, "Kevin Trebing" ***@***.***> wrote:

That sounds like the right process. What are the errors that you encountered then?

**Comment by wy22vv** [comment]
> At 2022-10-01 17:27:52, "Kevin Trebing" ***@***.***> wrote: That sounds like the right process. What are the errors that you encountered then? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by wy22vv** [comment]
I have explained it to you in detail in the email

**Comment by wy22vv** [comment]
> At 2022-10-01 17:27:52, "Kevin Trebing" ***@***.***> wrote: That sounds like the right process. What are the errors that you encountered then? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Because it's too long，I have explained it to you in detail in the email，

**Comment by HansBambel** [comment]
Closing, because errors were because of missing folder structure.
