### ISSUE TITLE
ImportError: cannot import name 'LearningRateLogger' from 'pytorch_lightning.callbacks'

### ISSUE THREAD

**Issue by ponyger** [HansBambel/SmaAt-UNet#26]
After searching for debug methods online,it tells me I  should use "from pytorch_lightning.loggers import LearningRateLogger
",cause the LearningRateLogger model is not in pytorch_lightning.callbacks, but after changing the way of import,still give me the ImportError. 
My version of pytorch_lightning is :
_**lightning-utilities     0.10.0
pytorch-lightning       2.1.2**_
 Any wrong? or Are there any other models to replace LearningRateLogger？

**Comment by HansBambel** [comment]
I think you are using the paper-snapshot branch, right? Because I can only find a `LearningRateMonitor` in the master branch. That version is using a quite old packages. You should check out the `requirements.txt` there for exact versions. For example pytorch-lightning is 0.7.6.

The name seemed to change in pytorch-lightning some releases back.

**Comment by ponyger** [comment]
Thank you for your reply.Yes,the error may due to the paper-snapshot branch. I use the master branch and seemed to solve the problem. 
**By the way,**the codes you uploaded in the master branch may have some mistakes? As far as I know, the **_lightning.pytorch_** should be **_pytorch_lightning_**? Writing lightning.pytorch seems to cause errors.
![image](https://github.com/HansBambel/SmaAt-UNet/assets/115455498/4231c7b4-64c3-45d8-a155-d9cb75b561f5)
![image](https://github.com/HansBambel/SmaAt-UNet/assets/115455498/96ae24ae-eb43-4fce-b48a-0b1150448a94)

**Comment by HansBambel** [comment]
Actually, both should work:
https://github.com/Lightning-AI/pytorch-lightning/discussions/16688
https://github.com/Lightning-AI/pytorch-lightning/discussions/17095

`pytorch_lightning` is the old way of importing and `lightning.pytorch` is the new way.
