### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by HLImg** [HansBambel/SmaAt-UNet#31]
Hello, can you provide the direct download links?

**Comment by HansBambel** [comment]
As written in the Readme:
> If you are interested in the dataset that we used please write an e-mail to: [k.trebing@alumni.maastrichtuniversity.nl](mailto:k.trebing@alumni.maastrichtuniversity.nl) and [s.mehrkanoon@uu.nl](mailto:s.mehrkanoon@uu.nl)
