### ISSUE TITLE
Sharing of model weights

### ISSUE THREAD

**Issue by Houangnt** [HansBambel/SmaAt-UNet#33]
Can you share your weight of paper ? I want use your weights for pretrain. I tried to train model but i have not resource for training so i only got accuracy around 0.77  
<img width="695" alt="Ảnh màn hình 2024-10-15 lúc 11 01 08" src="https://github.com/user-attachments/assets/a3a3ef63-4086-40f6-80a1-c8264e60f692">

**Comment by Houangnt** [comment]
![Uploading Ảnh màn hình 2024-10-15 lúc 11.01.08.png…]()

**Comment by HansBambel** [comment]
Hi! Yes, I could share the weights with you. They are around 50mb. Send me an email (in the README.md) and I can give you a link.

What do you want to do with them?

**Comment by Houangnt** [comment]
> Hi! Yes, I could share the weights with you. They are around 50mb. Send me an email (in the README.md) and I can give you a link.
> 
> What do you want to do with them?

I am a student and am currently working on a graduation project. My project instructor first wants to test the results and then wants to improve the model, but due to lack of resources, I I want to ask for your weight as a pretrain. Thank you for sharing the weight with me
