### ISSUE TITLE
Expected shape of `y_pred` vs `y` in `UNet_base` for precipitation prediction.

### ISSUE THREAD

**Issue by rutkovskii** [HansBambel/SmaAt-UNet#34]
Hello,

Thank you for your work!

I am in the process of adapting `UNetDS_Attention` to work with data coming from a different organization, but I encounter a point of confusion related to expected shapes in the training and validation steps.

**Question:**
What are the expected shapes of `x`, `y`, and `y_pred` inside `UNet_base` in training_step, if running the default setup with the original for precipitation?

---
**What I am trying to do:**

I am trying to use `UNetDS_Attention` to work with a data that comes from a different organization and I get the following:
```
x.shape = [16, 12, 256, 256]
y.shape = [16, 6, 256, 256]
y_pred.shape = [16, 256, 256]
```

Some parameters that I use (which are default):
```
batch_size = 16
n_channels = 12
n_classes = 1
num_input_images = 12 
num_output_images = 6
```

This arises acomplaint coming from the `loss_func`:
```
/Users/rutkovskii/Code/GitHub/ZinkResearch/SPRITE/SmaAt-UNet/models/regression_lightning.py:47: Using a target size (torch.Size([16, 6, 256, 256])) that is different to the input size (torch.Size([16, 256, 256])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
```

and then evidently, error:

```
RuntimeError: The size of tensor a (16) must match the size of tensor b (6) at non-singleton dimension 1
```

---

Thank you for your time!

**Comment by HansBambel** [comment]
Hi @rutkovskii,

The output-shape of `y_pred` is due to the architecture in `UNetDS_Attention`. In the default version there is a single `class` (-> feature map). If you want to get an output of 6 feature maps then you must change `n_classes = 6`.

I see now that the `num_output_images` parameter is misleading. What it meant was that the (single) target image is 6 steps ahead. It could be more aptly named `num_output_image`. Do you agree?

I hope this helps.

**Comment by rutkovskii** [comment]
So if I understand correctly:

`n_classes` defines number of predicted images.
`num_output_images` defines at what step the predicted image (if `n_classes = 1`)?

If `n_classes = 1` and `num_output_images = 6`, then 6th image is the one predicted by UNetDS_Attention?

**Comment by HansBambel** [comment]
1. Exactly
2. That depends on your data. When you have the data prepared in a way where the output images are 6 images in 5 minute intervals, then yes, the model should be able to learn that.
3. Yes!

**Comment by rutkovskii** [comment]
Thank you so much for clarifying! 
Wishing all the best with your work.
