### ISSUE TITLE
What is train.txt？

### ISSUE THREAD

**Issue by quetalangtaosh** [HansBambel/SmaAt-UNet#4]
I only have this dataset: RAD_NL25_RAC_5min_train_test_2016-2019.h5.
This dataset is placed inside the folder ：SmaAt-UNet-master\data\precipitation.
when I ran a file：train_SmaAtUNet.py, the following error occurs:

Traceback (most recent call last):
  File "D:\SmaAt-UNet-master\train_SmaAtUNet.py", line 127, in <module>
    voc_dataset_train = dataset_VOC.VOCSegmentation(dataset_folder, image_set='train',
  File "D:\SmaAt-UNet-master\utils\dataset_VOC.py", line 91, in __init__
    with open(os.path.join(split_f), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/PascalVOC\\VOCdevkit\\VOC2012\\ImageSets/Segmentation\\train.txt'

Can someone help me answer this question, thanks!

**Comment by HansBambel** [comment]
That script (`train_smaatunet.py`) is an example script for use of the network on another dataset. There the dataset is the PascalVOC as you can see in the error message. There the train.txt contains the image names of the training set.

To train the model on the precipitation dataset use the other script `train_precip_lightning.py`.
