### ISSUE TITLE
test

### ISSUE THREAD

**Issue by daralevian** [HansBambel/SmaAt-UNet#5]
I'm sorry to border that I have a question about the test_precip_lightning.py
i've run the train_precip_lightning.py and it has 60 epochs in the following folder 
![image](https://user-images.githubusercontent.com/107391441/231529434-bd432f86-8856-401d-9cbf-e5b4547a7586.png)
and I run the test file it has such error, I'd like to ask how to solve it.
![image](https://user-images.githubusercontent.com/107391441/231529725-fea7eaf4-1a35-421f-b48a-6add409f97aa.png)

**Comment by daralevian** [comment]
And if it will output pictures like the article?

**Comment by HansBambel** [comment]
You can find the answer to your first issue here: https://github.com/HansBambel/SmaAt-UNet/issues/3
You basically need to select the models that you want to compare and place them in the same folder. I named that folder `checkpoints/comparison`.

I also added a notebook just now that should get you going with the plots.

**Comment by daralevian** [comment]
thank you so much!
